server:
  port: 8083

spring:
  application:
    name: employee-chat-client

  ai:
    ollama:
      base-url: http://localhost:11434
      chat:
        options:
          model: qwen2.5:3b
          num_ctx: 4096
          num_thread: 8

    mcp:
      client:
        type: SYNC
        sse:
          connections:
            employee-mcp:
              url: http://localhost:8082
